### ISSUE TITLE
The “top” parameter is not working as expected

### ISSUE THREAD

**Issue by mprintz** [influxdata/influxdb-client-csharp#172] opened 2021-03-12 19:38 UTC
**Scenario:**
The following query is executed against the API:
https://localhost:44329/SOLAR/main/Series/NumericTimeSeries(a29da966-3966-470b-849c-b1d0bd3f9aa4)/Entries?$top=1

**Excepted result:**
Return the first entry

**Actual Results:**
All entries are returned.
 
**The Flux query:**
`from(bucket: p1) |> range(start: time(v: start_shifted)) |> drop(columns: ["_start", "_stop", "_measurement"]) |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") |> filter(fn: (r) => (r["series_id"] == p3)) |> sort(columns: [p4], desc: p5) |> limit(n: p7)`

The flux query looks correct, but I think that the issue is that the p7 parameter is incorrect.

**The following is the generated LINQ expression:**

```{aggregate([]).Where(e => (e.SeriesId == value(SE.OIP.Common.Repository.MongoDB.Series.SeriesEntryMongoRepository`1[SE.OIP.Common.Entities.Series.NumericSeriesEntry]).seriesId)).OrderBy($it => $it.Timestamp).Take(value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty).Take(60001)}```

 

As you can see, there are two “Take” expressions, the first one is equal to the value specified in the HTTP request(In this example its 1), however the Influx driver is taking the second one(which is the default Web API one).

__Specifications:__
 - Client Version:  1.17.0-dev.linq.13 LINQ driver
 - InfluxDB Version: 2.x and InfluxDB Cloud 2

**Comment by bednar** [comment] 2021-03-15 11:14
Hi @mprintz,

the issue is fixed in version: `1.17.0-dev.linq.15`: https://www.nuget.org/packages/InfluxDB.Client.Linq/1.17.0-dev.linq.15.

Regards

**Closed** 2021-03-15 16:45 UTC
Labels: bug
