### ISSUE TITLE
Exceptions risen from API methods

### ISSUE THREAD

**Issue by malessainray** [influxdata/influxdb-client-csharp#207] opened 2021-06-15 09:07 UTC
__Proposal:__
It would be benefitial if there was a native and easy to use solution which would allow us to know if a specific write operation was successful as we display this information to our users.

__Current behavior:__
We have to subscribe to the EventHandler and manually map the events risen to insertions we initiated.

__Desired behavior:__
A plain and simple way to know which call to the write method succeeded and which failed. This could be accomplished by throwing an exception if an error occured.

__Alternatives considered:__
Currently we are manually mapping the risen events to the calls to the write method but this is pretty error prone and not reliable.

__Use case:__
We display a result for every data operation our product performs and therefor need the information if the write was successfull or not and if not we need details why it wasn't (e.g. the exception)

**Comment by bednar** [comment] 2021-06-15 09:19
Hi @malessainray,

thanks for using our client.

The `WriteApi` uses background thread to batching data before are written into InfluxDB. It you would like to "directly" writes data into InfluxDB you can use `WriteApiAsync`.

The `WriteApiAsync` throws an exception if an error occured.

- https://github.com/influxdata/influxdb-client-csharp/blob/master/Client/WriteApiAsync.cs
- https://github.com/influxdata/influxdb-client-csharp/blob/master/Examples/WriteApiAsyncExample.cs
- https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#using-writeapiasync

Regards

**Comment by malessainray** [comment] 2021-06-15 19:18
Hi @bednar 

thank you for the very quick and helpful suggestion! Sadly I hit the next blocker as I always get a parsing error when I call `HealthAsync()` even though inserting to the InfluxDB Cloud works just fine.
This is the result I always get when calling the `HealthAsync()` method:
![image](https://user-images.githubusercontent.com/69465558/122110647-136ab380-ce1f-11eb-884c-11221844e83f.png)
and this is how I create my instance of the client:
![image](https://user-images.githubusercontent.com/69465558/122110414-ca1a6400-ce1e-11eb-9d9b-49f161f6bdef.png)

By the way: I was unable to find any documentation regarding the internal logging. Is there some URL you could point me towards where I could get the information on how to get the internal messages.

**Comment by bednar** [comment] 2021-06-16 06:54
> Hi @bednar
> 
> thank you for the very quick and helpful suggestion! Sadly I hit the next blocker as I always get a parsing error when I call `HealthAsync()` even though inserting to the InfluxDB Cloud works just fine.
> This is the result I always get when calling the `HealthAsync()` method:
> ![image](https://user-images.githubusercontent.com/69465558/122110647-136ab380-ce1f-11eb-884c-11221844e83f.png)
> and this is how I create my instance of the client:
> ![image](https://user-images.githubusercontent.com/69465558/122110414-ca1a6400-ce1e-11eb-9d9b-49f161f6bdef.png)

Unfortunately it is caused by https://github.com/influxdata/influxdb/issues/19357, as a workaround you can use something like:

```csharp
using var client = InfluxDBClientFactory.Create("http://localhost:8086", "my-token");
client.GetQueryApiSync().QuerySync("buckets()", "my-org");
```

> By the way: I was unable to find any documentation regarding the internal logging. Is there some URL you could point me towards where I could get the information on how to get the internal messages.

We don't have documentation about Logging, but you can enable logging via:

```csharp
using var client = InfluxDBClientFactory.Create("http://localhost:8086", "my-token");
client.SetLogLevel(LogLevel.Body);
```

Regards

**Comment by malessainray** [comment] 2021-06-16 07:53
> We don't have documentation about Logging, but you can enable logging via:

I've found this but where does it log to? How may I get the messages handled by my own log writer?

**Comment by bednar** [comment] 2021-06-16 08:03
You have to configure your log writer to handle the `InfluxDB.Client` namespace.

something like: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing#configure-network-tracing

**Comment by malessainray** [comment] 2021-06-16 08:30
> Unfortunately it is caused by [influxdata/influxdb#19357](https://github.com/influxdata/influxdb/issues/19357), as a workaround you can use something like:
> 
> ```cs
> using var client = InfluxDBClientFactory.Create("http://localhost:8086", "my-token");
> client.GetQueryApiSync().QuerySync("buckets()", "my-org");
> ```
> 
> >

Unfortunately when I use this exact snipped (with my token and bucket of course) I get the following exception:
```
System.MissingMethodException
  HResult=0x80131513
  Nachricht = Method not found: 'Void CsvHelper.CsvReader..ctor(System.IO.TextReader, System.Globalization.CultureInfo)'.
  Quelle = InfluxDB.Client.Core
  Stapelüberwachung:
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<>c.<.cctor>b__22_1(Exception e)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.QuerySync(RestRequest query, Action`2 consumer, Action`1 onError, Action onComplete)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.QuerySync(RestRequest query, IFluxResponseConsumer responseConsumer, Action`1 onError, Action onComplete)
   at InfluxDB.Client.QueryApiSync.QuerySync(Query query, String org)
   at InfluxDB.Client.QueryApiSync.QuerySync(String query, String org)
   at inray.OPCRouter.Influx2PlugIn.Runtime.Influx2PlugInInstance.FallbackHealthCheck() in D:\OR4\opcrouter4-plugins\OPCRouterInfluxDB2PlugIn\Runtime\Runtime\Influx2PlugInInstance.cs:line 64

```

**Comment by bednar** [comment] 2021-06-23 07:23
@malessainray, #209 is merged into master, you can use dev version of client by:

```console
dotnet add package InfluxDB.Client --version 2.0.0-dev.3368
```

**Comment by bednar** [comment] 2021-07-09 05:57
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.

**Closed by bednar** 2021-07-09 05:57 UTC
Labels: question
